version: "3.8"
services:
  air-quality:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    env_file: .env
    depends_on: [ db ]
    restart: unless-stopped
    environment:
      - APP_ENV=development
  db:
    image: postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_vol:
