version: "3.8"
services:
  test-air-quality:
    build:
      context: .
      target: test
    ports:
      - "3001:3001"
    env_file: .env.testing
    depends_on: [ test-db ]
    restart: "no"
    environment:
      APP_ENV: "test"
      APP_PORT: 3001
  test-db:
    image: postgres
    env_file: .env.testing
    ports:
      - "5432"