version: "3.8"
services:
  test-air-quality:
    build:
      context: .
    ports:
      - "3001:3001"
    env_file: .env.testing
    depends_on: [ db ]
    restart: "no"
    environment:
      APP_ENV: "test"
  test_db:
    image: postgres
    env_file: .env.testing
    ports:
      - "5433:5432"